const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const text=(s,status=200)=>new Response(s,{status,headers:{'content-type':'text/plain; charset=utf-8'}});
const id=()=>crypto.randomUUID();
const now=()=>new Date().toISOString();
async function sign(value,secret){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value));return `${value}.${[...new Uint8Array(sig)].map(x=>x.toString(16).padStart(2,'0')).join('')}`;}
async function verify(token,secret){if(!token||!secret)return false;const i=token.lastIndexOf('.');if(i<1)return false;const value=token.slice(0,i);return token===await sign(value,secret)&&Number(value.split('.')[1])>Date.now();}
function cookie(name,value,maxAge){return `${name}=${value}; Max-Age=${maxAge}; Path=/; HttpOnly; Secure; SameSite=Lax`}
async function auth(req,env){const c=req.headers.get('Cookie')||'';const m=c.match(/mokova_session=([^;]+)/);return verify(m?.[1],env.SESSION_SECRET||'CHANGE_ME');}
async function rows(env,sql,...args){return (await env.DB.prepare(sql).bind(...args).all()).results||[];}
async function bootstrap(env){
 const ps=await rows(env,'SELECT data FROM products WHERE active=1 ORDER BY json_extract(data,\'$.sortOrder\'), name');
 const cs=await rows(env,'SELECT data FROM categories WHERE active=1 ORDER BY sort_order,name');
 const rs=await rows(env,'SELECT data FROM reviews WHERE visible=1 ORDER BY created_at DESC');
 const bs=await rows(env,'SELECT data FROM banners WHERE active=1 ORDER BY sort_order');
 const faq=await rows(env,'SELECT value FROM settings WHERE key=?','faq');
 const site=await rows(env,'SELECT value FROM settings WHERE key=?','site');
 const blog=await rows(env,"SELECT data FROM blog_posts WHERE status='published' ORDER BY published_at DESC");
 const pages=await rows(env,'SELECT slug,data FROM pages WHERE active=1 ORDER BY slug');
 const gallery=await rows(env,'SELECT data FROM gallery WHERE active=1 ORDER BY sort_order');
 return {products:ps.map(x=>JSON.parse(x.data)),categories:cs.map(x=>JSON.parse(x.data)),reviews:rs.map(x=>JSON.parse(x.data)),site:site[0]?JSON.parse(site[0].value):{banners:bs.map(x=>JSON.parse(x.data))},faq:faq[0]?JSON.parse(faq[0].value):[],blog:blog.map(x=>JSON.parse(x.data)),pages:Object.fromEntries(pages.map(x=>[x.slug,JSON.parse(x.data)])),gallery:gallery.map(x=>JSON.parse(x.data))};
}
async function seedIfEmpty(env){const c=await env.DB.prepare('SELECT COUNT(*) n FROM products').first();if(Number(c?.n||0)>0)return;return;}
async function sendIntegration(env,payload){if(!env.GOOGLE_APPS_SCRIPT_URL)return;try{await fetch(env.GOOGLE_APPS_SCRIPT_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});}catch(e){}}
export default {async fetch(req,env){const url=new URL(req.url);const path=url.pathname;
 try{
  if(path==='/api/bootstrap')return json(await bootstrap(env));
  if(path==='/api/analytics'&&req.method==='POST'){const b=await req.json();const allowed=['view','share','whatsapp','review','enquiry'];if(!allowed.includes(b.type))return json({error:'Invalid event'},400);await env.DB.prepare('INSERT INTO analytics_events(type,product_id,path) VALUES(?,?,?)').bind(b.type,b.productId||null,url.pathname).run();return json({ok:true});}
  if(path==='/api/enquiry'&&req.method==='POST'){const b=await req.json();const eid=id();await env.DB.prepare('INSERT INTO enquiries(id,data) VALUES(?,?)').bind(eid,JSON.stringify({...b,id:eid,created_at:now()})).run();await sendIntegration(env,{type:'enquiry',...b,id:eid,created_at:now()});return json({ok:true,id:eid});}
  if(path==='/api/admin/login'&&req.method==='POST'){const b=await req.json();if(!env.ADMIN_PASSWORD||b.password!==env.ADMIN_PASSWORD)return json({error:'Unauthorized'},401);const exp=Date.now()+1000*60*60*12;const token=await sign(`${id()}.${exp}`,env.SESSION_SECRET||'CHANGE_ME');return json({ok:true},{'set-cookie':cookie('mokova_session',token,60*60*12)});}
  if(path==='/api/admin/me'&&req.method==='GET')return (await auth(req,env))?json({ok:true}):json({error:'Unauthorized'},401);
  if(path==='/api/admin/data'&&req.method==='GET'){if(!(await auth(req,env)))return json({error:'Unauthorized'},401);const d=await bootstrap(env);const enquiries=await rows(env,'SELECT data FROM enquiries ORDER BY created_at DESC LIMIT 200');const blog=await rows(env,'SELECT data FROM blog_posts ORDER BY updated_at DESC');const analytics=await rows(env,'SELECT type,COUNT(*) n FROM analytics_events GROUP BY type');const siteRows=await rows(env,'SELECT value FROM settings WHERE key=?','site');return json({...d,enquiries:enquiries.map(x=>JSON.parse(x.data)),blog:blog.map(x=>JSON.parse(x.data)),analytics:Object.fromEntries(analytics.map(x=>[x.type,Number(x.n)])),site:siteRows[0]?JSON.parse(siteRows[0].value):d.site});}
  if(path==='/api/admin/products'&&req.method==='PUT'){if(!(await auth(req,env)))return json({error:'Unauthorized'},401);const list=await req.json();for(const p of list){await env.DB.prepare('INSERT OR REPLACE INTO products(id,name,slug,data,active,updated_at) VALUES(?,?,?,?,?,?)').bind(p.id,p.name,p.slug||p.id,JSON.stringify(p),p.active===false?0:1,now()).run();}return json({ok:true,data:await bootstrap(env)});}
  if(path==='/api/admin/reviews'&&req.method==='PUT'){if(!(await auth(req,env)))return json({error:'Unauthorized'},401);const list=await req.json();for(const r of list){await env.DB.prepare('INSERT OR REPLACE INTO reviews(id,product_id,name,email,rating,comment,reply,visible,data) VALUES(?,?,?,?,?,?,?,?,?)').bind(r.id||id(),r.productId||r.product_id||null,r.reviewer_name||r.name||'',r.reviewer_email||r.email||'',Number(r.rating||5),r.comment||'',r.reply||'',r.visible===false?0:1,JSON.stringify(r)).run();}return json({ok:true,data:await bootstrap(env)});}
  if(path==='/api/admin/blog'&&req.method==='PUT'){if(!(await auth(req,env)))return json({error:'Unauthorized'},401);const list=await req.json();for(const p of list){await env.DB.prepare('INSERT OR REPLACE INTO blog_posts(id,slug,title,data,status,published_at,updated_at) VALUES(?,?,?,?,?,?,?)').bind(p.id||id(),p.slug,p.title,JSON.stringify(p),p.status||'draft',p.status==='published'?(p.published_at||now()):null,now()).run();}return json({ok:true,data:await bootstrap(env)});}
  if(path==='/api/admin/pages'&&req.method==='PUT'){if(!(await auth(req,env)))return json({error:'Unauthorized'},401);const pages=await req.json();for(const [slug,data] of Object.entries(pages))await env.DB.prepare('INSERT OR REPLACE INTO pages(id,slug,data,active) VALUES(?,?,?,1)').bind(slug,slug,JSON.stringify(data)).run();return json({ok:true,data:await bootstrap(env)});}
  if(path==='/api/admin/gallery'&&req.method==='PUT'){if(!(await auth(req,env)))return json({error:'Unauthorized'},401);const list=await req.json();for(let i=0;i<list.length;i++){const g=list[i];await env.DB.prepare('INSERT OR REPLACE INTO gallery(id,data,active,sort_order) VALUES(?,?,?,?)').bind(g.id||id(),JSON.stringify(g),g.active===false?0:1,i).run();}return json({ok:true,data:await bootstrap(env)});}
  if(path==='/api/admin/site'&&req.method==='PUT'){if(!(await auth(req,env)))return json({error:'Unauthorized'},401);const site=await req.json();await env.DB.prepare('INSERT OR REPLACE INTO settings(key,value,updated_at) VALUES(?,?,?)').bind('site',JSON.stringify(site),now()).run();for(const [i,b] of (site.banners||[]).entries())await env.DB.prepare('INSERT OR REPLACE INTO banners(id,data,active,sort_order) VALUES(?,?,?,?)').bind(b.id||`banner-${i}`,JSON.stringify(b),b.active===false?0:1,i).run();return json({ok:true,data:await bootstrap(env)});}
  if(path==='/api/admin/upload'&&req.method==='POST'){if(!(await auth(req,env)))return json({error:'Unauthorized'},401);if(!env.MEDIA_BUCKET)return json({error:'R2 binding missing'},503);const form=await req.formData();const file=form.get('file');if(!file||typeof file.arrayBuffer!=='function')return json({error:'File required'},400);const ext=(file.name?.split('.').pop()||'bin').replace(/[^a-z0-9]/gi,'');const key=`uploads/${crypto.randomUUID()}.${ext}`;await env.MEDIA_BUCKET.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type||'application/octet-stream'}});return json({ok:true,key,url:`/media/${key}`});}
  if(path.startsWith('/media/')&&req.method==='GET'){if(!env.MEDIA_BUCKET)return text('R2 not configured',404);const key=path.slice('/media/'.length);const obj=await env.MEDIA_BUCKET.get(key);if(!obj)return text('Not found',404);return new Response(obj.body,{headers:{'content-type':obj.httpMetadata?.contentType||'application/octet-stream','cache-control':'public,max-age=31536000'}});}
  if(env.ASSETS){const asset=await env.ASSETS.fetch(req);if(asset.status!==404)return asset;return env.ASSETS.fetch(new Request(new URL('/index.html',url),req));}return text('Not found',404);
 }catch(e){return json({error:e.message||'Server error'},500)}}};
